--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/zZPROGAMERZz423/RankShopSystem
branches:
- master
projects:
  RankShopSystem:
    path: ""
    icon: RankShopSystem.png
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
...
