name: RankShopSystem
version: 1.0.0
main: zZPROGAMERZz423\RankShopSystem\Main
api: [3.8.3]
author: zZPROGAMERZz423 | §eFor issues report by §2Visiting GitHub.com/zZPROGAMERZz423

depend: [PureChat, PurePerms, EconomyAPI]
commands:
  rshop:
   description: "A rank shop system established for servers"
